### ISSUE TITLE
Not working on IE11... :(

### ISSUE THREAD

**Issue by fbzoltan** [marrio-h/universal-parallax#10]
Not working on IE11... :(

**Comment by dark705** [comment]
In universal-parallax.js try
Object.assign(parallax[i].style, {
	'background-repeat': 'no-repeat',
	'background-position': 'center',
	'background-size': 'cover'
})
replace to
	parallax[i].style.backgroundRepeat = 'no-repeat';
	parallax[i].style.backgroundPosition = 'center';
	parallax[i].style.backgroundSize = 'cover';

**Comment by marrio-h** [comment]
Nice @dark705 - didn't consider Object.assign.
- I'll add it with the next push!

Thanks.

**Comment by marrio-h** [comment]
Added 👍🏼
