### ISSUE TITLE
Does it work with reponsive images?

### ISSUE THREAD

**Issue by invasi0n** [marrio-h/universal-parallax#12]
Hello,

The README.md files doesn't give information about using the script with responsive images.
Does it work?

Thank you~

**Comment by marrio-h** [comment]
Hi,

It depends on how intend to use your images.
1. The script works by making a new background layer inside whatever container you've defined.
2. From there you can modify the image with CSS how you like.

If you have a setup that swaps out images based on resolution then simply add that inside the `data-parallax-image="path/to/your_image"` attribute.

Hope that answers your question :)
