### ISSUE TITLE
Choppy scroll on Safari on mac

### ISSUE THREAD

**Issue by websimon** [marrio-h/universal-parallax#4]
I´m using your parallax in a web project and it works really well except in safari (on mac desktop). The scroll is choppy and not smooth at all. Any ideas?

**Comment by marrio-h** [comment]
Hi websimon. Pushed a new version now and fixed the problem. Thanks for using the plugin and letting me know!

**Comment by websimon** [comment]
Thank you! I´ll give it a try as soon as possible!
