### ISSUE TITLE
effects not working

### ISSUE THREAD

**Issue by Deminghuman** [marrio-h/universal-parallax#5]
By including the .js and .css files in the dist directory and running the required script the parallax effect does not work. The demo you have included works but the .css is different on the section containers. Is this project only supposed to run via the demo's CSS?

**Comment by marrio-h** [comment]
Hi. Thank you for noticing me! It's not supposed to only work in the demo - I'll correct this asap (been on holiday and on the last push must have missed something).

Will post again when fixed.

**Comment by Deminghuman** [comment]
Thanks Marrio.

**Comment by marrio-h** [comment]
Hi again Deminghuman,

I've uploaded improvements and assured that it works following the steps provided. Please try again and let me know how you get on :)

/m
