### ISSUE TITLE
Scrolling issues on Samsung Galaxy S9's default browser

### ISSUE THREAD

**Issue by rsdev88** [marrio-h/universal-parallax#6]
Hi I tried this on a Galaxy S9 - it works perfectly in Chrome but in the phone's default browser, all of the background pictures are at the top and stacked on top of one another, with the final section's background picture sitting on top. When you scroll to the bottom of the content and then begin to scroll back up, you can see the other background images creeping out from underneath. This occurs in the demo as well.

**Comment by rsdev88** [comment]
Hi marrio-h, I just updated my site to use the your latest changes and they've fixed the S9 browser issue. I also re-tested in Chrome and iOS (on BrowserStack) and it's working great. Thanks very much for the quick reply and fix!

**Comment by marrio-h** [comment]
Awesome! I'm really glad it works.
I tried to check it on Android there myself but it wouldn't load for some reason, but thank you for your comment and for testing it.

/m
