### ISSUE TITLE
Image jumps on initial scroll

### ISSUE THREAD

**Issue by SeanTurtle** [marrio-h/universal-parallax#9]
Hi there

Image is in place on initial load, but as soon as you start to scroll it jumps down approximately 100px, and scrolls smoothly. Any help would be greatly appreciated.

Cheers
Sean

**Comment by marrio-h** [comment]
Hi,

Thanks for the feedback.
Where are you experiencing this? Desktop/mobile(iOS, Android), other?

Best

**Comment by SeanTurtle** [comment]
Hi Mario

Sorry, desktop (Mac) in Chrome.

Cheers
Sean

**Comment by SeanTurtle** [comment]
Sorry, it was a class with some css - my mistake!

**Comment by marrio-h** [comment]
hehe ok good - glad you sorted it out! :)
